### ISSUE TITLE
read_file creates empty files

### ISSUE THREAD

**Issue by pigfrown** [storj-thirdparty/uplink-python#13]
read_file is not writing to the file handle. The empty check on the "buf"output from read() is wrong. See pull request

https://github.com/storj-thirdparty/uplink-python/pull/12

**Comment by kmozurkewich** [comment]
@pigfrown  - just merged PR.  Can you confirm your issue is resolved?


Thanks!

**Comment by pigfrown** [comment]
Yep working for me now, thanks :)

**Comment by kmozurkewich** [comment]
sweeeet.  thank you for the contrib!
