### ISSUE TITLE
What are API keys?

### ISSUE THREAD

**Issue by pickaxe828** [storj-thirdparty/uplink-python#18]
What are API keys? Where can I find them in my bucket/ account?

**Comment by Erikvv** [comment]
They are no longer visible in the GUI. API key is part of the serialized access grant. Serialized access can do everything an API key can.

```
access = uplink.parse_access("1JRC...")
```

If you really want to extract the API key you can do it with uplink-cli:

```
uplink access inspect 1JdRC...
```

**Comment by pickaxe828** [comment]
Oh thank you for the solution
It works now :>
