### ISSUE TITLE
Bucket name

### ISSUE THREAD

**Issue by ghost** [storj-thirdparty/uplink-python#25]
Hello
.. Does it make sense add lower() to bucket name in project.py ?
https://github.com/storj-thirdparty/uplink-python/blob/efba0bc50803599d4570376ad1fd737e0db65b46/uplink_python/project.py#L121

an upper case letter in bucket name causes the "internal error message" 
or "bucket invalid name" in Uplink CLI

Thank you

**Comment by kmozurkewich** [comment]
Thanks for the feedback!  While that would be a convenience decorator, the bindings should pass-through behavior from the standard libraries, even if errors are generated.  We can keep this open for further feedback.
