### ISSUE TITLE
Add to the README how to run the local tests

### ISSUE THREAD

**Issue by ifraixedes** [storj-thirdparty/uplink-python#5]
I'm playing around with this implementation and I'm wondering how to turn the tests in my local environment.

I'm not a python experienced developer so it may be something easy but I'd appreciate it if you could add that information to the README.

This kind of information helps to receive contributions.

**Comment by ayush-srivastava-03** [comment]
@ifraixedes 
Instructions to run unit-test cases on local has been added to README.

[Run Unit Test Cases on Local](https://github.com/storj-thirdparty/uplink-python#run-unit-test-cases-on-local)
